[theme]
base = "light"

# メインカラー（ミントグリーン）
primaryColor = "#2bd698"

# 背景色
# まぶしくないように、ほんの少しグレーを混ぜた「ペールミントグレー」にしました
backgroundColor = "#F2F5F4"

# サイドバーなどの背景色
# 背景より少しだけ濃くして、境界をわかりやすく
secondaryBackgroundColor = "#E3EBE8"

# 文字色
textColor = "#384242"
